import { NextResponse } from 'next/server'
import devLog from '@/utils/dev/logger'
import { createRateLimiter } from '@/utils/api/rateLimit'
import {
  GatewayValidationError,
  buildGatewayTargetUrl,
  extractBearerHeader,
  resolveGatewayBaseUrl,
} from '@/utils/api/gatewayProxy'

const checkRate = createRateLimiter({ windowMs: 60_000, maxRequests: 10 })

/**
 * GET /api/simulations/proxy?labId=...&reservationKey=...&gatewayUrl=...
 *
 * Downloads a reservation-scoped FMU proxy generated by the provider gateway.
 */
export async function GET(request) {
  const { limited } = checkRate(request)
  if (limited) {
    return NextResponse.json({ error: 'Too many requests - please try again later' }, { status: 429 })
  }

  try {
    const { searchParams } = new URL(request.url)
    const labId = searchParams.get('labId')
    const reservationKey = searchParams.get('reservationKey')
    const gatewayUrl = searchParams.get('gatewayUrl')

    if (!labId) {
      return NextResponse.json({ error: 'Missing required parameter: labId' }, { status: 400 })
    }
    if (!reservationKey) {
      return NextResponse.json({ error: 'Missing required parameter: reservationKey' }, { status: 400 })
    }

    const gatewayBaseUrl = await resolveGatewayBaseUrl({ labId, gatewayUrl, requireLabMatch: true })
    const targetUrl = buildGatewayTargetUrl(
      gatewayBaseUrl,
      `/fmu/api/v1/fmu/proxy/${encodeURIComponent(labId)}`,
      { reservationKey },
    )
    const authorization = extractBearerHeader(request)

    devLog.log(`[simulations/proxy] Proxying download to ${targetUrl}`)

    const gatewayRes = await fetch(targetUrl, {
      headers: {
        ...(authorization ? { Authorization: authorization } : {}),
      },
      cache: 'no-store',
    })

    if (!gatewayRes.ok) {
      const errBody = await gatewayRes.text()
      devLog.error(`[simulations/proxy] Gateway returned ${gatewayRes.status}: ${errBody}`)
      return NextResponse.json(
        { error: `Gateway error (${gatewayRes.status})`, details: errBody },
        { status: gatewayRes.status },
      )
    }

    const contentType = gatewayRes.headers.get('content-type') || 'application/octet-stream'
    const disposition = gatewayRes.headers.get('content-disposition') || 'attachment; filename="fmu-proxy.fmu"'

    return new Response(gatewayRes.body, {
      status: 200,
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': disposition,
      },
    })
  } catch (error) {
    if (error instanceof GatewayValidationError) {
      return NextResponse.json({ error: error.message }, { status: error.status || 400 })
    }
    devLog.error('[simulations/proxy] Proxy error:', error)
    return NextResponse.json({ error: error.message || 'Internal proxy error' }, { status: 500 })
  }
}
