import { NextResponse } from 'next/server'
import devLog from '@/utils/dev/logger'
import { createRateLimiter, createRateLimitResponse } from '@/utils/api/rateLimit'
import { HttpError, handleGuardError } from '@/utils/auth/guards'
import {
  GatewayValidationError,
  buildGatewayTargetUrl,
  gatewayFetch,
  resolveLabAccessGateway,
} from '@/utils/api/gatewayProxy'
import { requireFmuUserBinding, resolveFmuGatewayHeaders } from '@/utils/auth/fmuGatewayContext'
import { publicErrorResponse } from '@/utils/security/publicError'

const checkRate = createRateLimiter({ operation: 'simulation-proxy', windowMs: 60_000, maxRequests: 10 })

/**
 * GET /api/simulations/proxy?labId=...&reservationKey=...
 *
 * Downloads a reservation-scoped FMU proxy generated by the provider gateway.
 */
export async function GET(request) {
  try {
    const userBinding = await requireFmuUserBinding()
    const rateLimitResponse = createRateLimitResponse(await checkRate(request, { userId: userBinding }))
    if (rateLimitResponse) return rateLimitResponse
    const { searchParams } = new URL(request.url)
    const labId = searchParams.get('labId')
    const reservationKey = searchParams.get('reservationKey')

    if (!labId) {
      return NextResponse.json({ error: 'Missing required parameter: labId' }, { status: 400 })
    }
    if (!reservationKey) {
      return NextResponse.json({ error: 'Missing required parameter: reservationKey' }, { status: 400 })
    }

    const gatewayBaseUrl = await resolveLabAccessGateway({ labId })
    const targetUrl = buildGatewayTargetUrl(
      gatewayBaseUrl,
      `/fmu/api/v1/fmu/proxy/${encodeURIComponent(labId)}`,
      { reservationKey },
    )
    const gatewayHeaders = resolveFmuGatewayHeaders(request, {
      labId,
      reservationKey,
      gatewayOrigin: gatewayBaseUrl,
      userBinding,
    })

    devLog.log(`[simulations/proxy] Proxying download to ${targetUrl}`)

    const gatewayRes = await gatewayFetch(targetUrl, {
      headers: {
        ...gatewayHeaders,
      },
      cache: 'no-store',
    })

    if (!gatewayRes.ok) {
      const errBody = await gatewayRes.text()
      devLog.error(`[simulations/proxy] Gateway returned ${gatewayRes.status}`, { bodyBytes: errBody.length })
      return publicErrorResponse({
        status: gatewayRes.status,
        code: 'GATEWAY_REQUEST_FAILED',
        message: 'The simulation proxy could not be downloaded.',
        error: new Error(`Gateway returned ${gatewayRes.status}`),
        context: 'simulations-proxy-gateway',
      })
    }

    const contentType = gatewayRes.headers.get('content-type') || 'application/octet-stream'
    const disposition = gatewayRes.headers.get('content-disposition') || 'attachment; filename="fmu-proxy.fmu"'

    return new Response(gatewayRes.body, {
      status: 200,
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': disposition,
      },
    })
  } catch (error) {
    if (error instanceof HttpError) return handleGuardError(error, request)
    if (error instanceof GatewayValidationError) {
      return publicErrorResponse({
        status: error.status || 400,
        code: 'INVALID_GATEWAY_REQUEST',
        message: 'The simulation proxy parameters are invalid.',
        error,
        context: 'simulations-proxy-validation',
      })
    }
    return publicErrorResponse({
      status: 500,
      code: 'SIMULATION_PROXY_FAILED',
      message: 'The simulation proxy could not be downloaded.',
      error,
      context: 'simulations-proxy',
    })
  }
}
