"use client";

import { useCallback, useEffect, useRef, useState } from 'react';
import PropTypes from 'prop-types';
import { useUser } from '@/context/UserContext';
import { useNotifications } from '@/context/NotificationContext';
import { hasInstitutionRegistrationPrivilege } from '@/utils/auth/roleValidation';
import devLog from '@/utils/dev/logger';
import {
  notifyInstitutionProvisioningAccessDenied,
  notifyInstitutionProvisioningGenerated,
  notifyInstitutionProvisioningGenerationFailed,
} from '@/utils/notifications/institutionToasts';

const PAIRING_STATUS_INTERVAL_MS = 3000;

function statusLabel(status) {
  return String(status || '').replaceAll('_', ' ').toLowerCase();
}

function formatPairingExpiry(value) {
  if (!value) return '-';
  const numericValue = Number(value);
  const date = Number.isFinite(numericValue)
    ? new Date(numericValue * 1000)
    : new Date(value);
  return Number.isNaN(date.getTime()) ? '-' : date.toLocaleString();
}

export default function InstitutionInviteCard({
  className = '',
  defaultTokenType = 'provider',
  lockTokenType = false,
  autoGenerate = false,
}) {
  const { isSSO, user } = useUser();
  const { addTemporaryNotification } = useNotifications();
  const [tokenType, setTokenType] = useState(defaultTokenType);
  const [pairing, setPairing] = useState(null);
  const [loading, setLoading] = useState(false);
  const [approving, setApproving] = useState(false);
  const autoGeneratedRef = useRef(false);

  const canRegisterInstitution = isSSO && user && hasInstitutionRegistrationPrivilege(user);

  useEffect(() => {
    setTokenType(defaultTokenType);
  }, [defaultTokenType]);

  const loadPairingStatus = useCallback(async (pairingId) => {
    if (!pairingId) return;
    try {
      const response = await fetch(`/api/institutions/provisioning/pairings/${pairingId}`, {
        credentials: 'include',
      });
      if (!response.ok) return;
      const data = await response.json();
      setPairing((current) => ({ ...current, ...data }));
    } catch (error) {
      devLog.error('InstitutionInviteCard: pairing status failed', error);
    }
  }, []);

  useEffect(() => {
    if (!pairing?.pairingId || !['AWAITING_BACKEND', 'AWAITING_APPROVAL'].includes(pairing.status)) {
      return undefined;
    }
    const timer = setInterval(() => loadPairingStatus(pairing.pairingId), PAIRING_STATUS_INTERVAL_MS);
    return () => clearInterval(timer);
  }, [pairing?.pairingId, pairing?.status, loadPairingStatus]);

  const createPairing = useCallback(async () => {
    if (!isSSO || !canRegisterInstitution) {
      notifyInstitutionProvisioningAccessDenied(addTemporaryNotification, tokenType);
      return;
    }

    setLoading(true);
    try {
      const response = await fetch('/api/institutions/provisioning/pairings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ registrationType: tokenType }),
      });
      const data = await response.json().catch(() => ({}));
      if (!response.ok) {
        throw new Error(data?.error || 'Failed to create pairing challenge');
      }
      setPairing(data);
      notifyInstitutionProvisioningGenerated(addTemporaryNotification, tokenType);
    } catch (error) {
      devLog.error('InstitutionInviteCard: Failed to create pairing challenge', error);
      notifyInstitutionProvisioningGenerationFailed(
        addTemporaryNotification,
        tokenType,
        error?.message || 'Failed to create pairing challenge',
      );
    } finally {
      setLoading(false);
    }
  }, [addTemporaryNotification, canRegisterInstitution, isSSO, tokenType]);

  const approvePairing = useCallback(async () => {
    if (!pairing?.pairingId) return;
    setApproving(true);
    try {
      const response = await fetch(
        `/api/institutions/provisioning/pairings/${pairing.pairingId}/approve`,
        { method: 'POST', credentials: 'include' },
      );
      const data = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(data?.error || 'Failed to approve pairing');
      setPairing((current) => ({ ...current, ...data, status: 'APPROVED' }));
    } catch (error) {
      devLog.error('InstitutionInviteCard: Failed to approve pairing', error);
      notifyInstitutionProvisioningGenerationFailed(
        addTemporaryNotification,
        tokenType,
        error?.message || 'Failed to approve pairing',
      );
    } finally {
      setApproving(false);
    }
  }, [addTemporaryNotification, pairing?.pairingId, tokenType]);

  useEffect(() => {
    if (!autoGenerate || autoGeneratedRef.current || loading || pairing || !canRegisterInstitution) return;
    autoGeneratedRef.current = true;
    createPairing();
  }, [autoGenerate, canRegisterInstitution, createPairing, loading, pairing]);

  if (!canRegisterInstitution) return null;

  return (
    <div className={`bg-white shadow-md rounded-lg p-6 mt-6 mb-6 ${className}`}>
      <h1 className="text-2xl font-bold text-center mb-4 text-gray-800">
        Institutional Backend Pairing
      </h1>
      <p className="text-sm text-gray-600 mb-4">
        Generate a short-lived challenge and enter it in your institutional backend. The backend
        supplies its configured wallet and public origin; this page never accepts either value.
      </p>

      {pairing && (
        <div className="space-y-3 mb-6">
          <div className="border rounded p-3 bg-gray-50">
            <p className="text-xs font-semibold text-gray-700">Pairing challenge</p>
            <textarea
              className="w-full mt-1 text-xs font-mono border rounded p-2 bg-white text-gray-800"
              value={pairing.challenge || ''}
              readOnly
              rows={3}
              aria-label="Pairing challenge"
            />
            <p className="text-xs text-gray-500 mt-1">
              Status: {statusLabel(pairing.status)}. Expires at:{' '}
              {formatPairingExpiry(pairing.expiresAt)}
            </p>
          </div>

          {pairing.walletAddress && pairing.canonicalBackendOrigin && (
            <div className="grid gap-2 text-xs text-gray-700">
              <div className="border rounded p-2 bg-gray-50">
                <p className="font-semibold">Institutional wallet</p>
                <p className="break-all font-mono">{pairing.walletAddress}</p>
              </div>
              <div className="border rounded p-2 bg-gray-50">
                <p className="font-semibold">Canonical backend origin</p>
                <p className="break-all font-mono">{pairing.canonicalBackendOrigin}</p>
              </div>
            </div>
          )}

          {pairing.status === 'AWAITING_APPROVAL' && (
            <button
              type="button"
              onClick={approvePairing}
              disabled={approving}
              className="w-full rounded bg-brand px-4 py-2 font-semibold text-white disabled:opacity-60"
            >
              {approving ? 'Approving pairing...' : 'Approve pairing and issue token'}
            </button>
          )}

          {pairing.status === 'APPROVED' && (
            <p className="rounded border border-green-200 bg-green-50 p-3 text-sm text-green-900">
              Pairing approved. Return to the institutional backend and finalize registration.
            </p>
          )}
        </div>
      )}

      {!lockTokenType && (
        <div className="mb-4 border-b pb-4">
          <label className="block text-sm font-semibold text-gray-700 mb-2">Institution type</label>
          <div className="flex gap-4">
            <label className="flex items-center cursor-pointer">
              <input
                type="radio"
                name="tokenType"
                value="provider"
                checked={tokenType === 'provider'}
                onChange={(event) => setTokenType(event.target.value)}
                className="mr-2"
              />
              <span className="text-sm">Provider</span>
            </label>
            <label className="flex items-center cursor-pointer">
              <input
                type="radio"
                name="tokenType"
                value="consumer"
                checked={tokenType === 'consumer'}
                onChange={(event) => setTokenType(event.target.value)}
                className="mr-2"
              />
              <span className="text-sm">Consumer</span>
            </label>
          </div>
        </div>
      )}

      <button
        type="button"
        onClick={createPairing}
        disabled={loading}
        className="w-full rounded bg-brand px-4 py-2 font-semibold text-white disabled:opacity-60"
      >
        {loading ? 'Generating challenge...' : 'Generate pairing challenge'}
      </button>
    </div>
  );
}

InstitutionInviteCard.propTypes = {
  className: PropTypes.string,
  defaultTokenType: PropTypes.oneOf(['provider', 'consumer']),
  lockTokenType: PropTypes.bool,
  autoGenerate: PropTypes.bool,
};
