import * as onboarding from '../index'

describe('onboarding barrel exports', () => {
  it('should export all expected members', () => {
    expect(typeof onboarding.resolveInstitutionalBackendUrl).toBe('function')
    expect(typeof onboarding.hasInstitutionalBackend).toBe('function')
    expect(typeof onboarding.clearBackendCache).toBe('function')
    expect(typeof onboarding.OnboardingStatus).toBe('object')
    expect(typeof onboarding.OnboardingErrorCode).toBe('object')
    expect(typeof onboarding.extractStableUserId).toBe('function')
    expect(typeof onboarding.initiateInstitutionalOnboarding).toBe('function')
    expect(typeof onboarding.checkOnboardingStatus).toBe('function')
    expect(typeof onboarding.pollOnboardingStatus).toBe('function')
    expect(typeof onboarding.checkUserOnboardingStatus).toBe('function')
    expect(typeof onboarding.storeOnboardingResult).toBe('function')
    expect(typeof onboarding.getOnboardingResult).toBe('function')
    expect(typeof onboarding.findResultByUser).toBe('function')
    expect(typeof onboarding.clearOnboardingResult).toBe('function')
    expect(typeof onboarding.clearUserResults).toBe('function')
    expect(typeof onboarding.getStoreStats).toBe('function')
    expect(typeof onboarding.isOnboardingCallbackSignatureRequired).toBe('function')
    expect(typeof onboarding.getOnboardingCallbackSecret).toBe('function')
    expect(typeof onboarding.canVerifyOnboardingCallbackSignature).toBe('function')
    expect(typeof onboarding.issueOnboardingCallbackToken).toBe('function')
    expect(typeof onboarding.extractCallbackTokenFromRequest).toBe('function')
    expect(typeof onboarding.verifyOnboardingCallbackToken).toBe('function')
    expect(typeof onboarding.computeOnboardingCallbackHmac).toBe('function')
    expect(typeof onboarding.verifyOnboardingCallbackHmac).toBe('function')
    expect(typeof onboarding.buildSignedOnboardingCallbackUrl).toBe('function')
  })
})
