import fs from 'node:fs'
import path from 'node:path'
import { createHash, createPublicKey } from 'node:crypto'

export const MARKETPLACE_JWT_ALGORITHM = 'RS256'

const STATIC_PUBLIC_KEY_PATH = path.join(
  process.cwd(),
  'public',
  '.well-known',
  'public-key.pem',
)
const STATIC_JWKS_PATH = path.join(
  process.cwd(),
  'public',
  '.well-known',
  'jwks.json',
)

function assertPem(publicKeyPem, label = 'public key') {
  if (typeof publicKeyPem !== 'string'
    || !publicKeyPem.includes('-----BEGIN PUBLIC KEY-----')
    || !publicKeyPem.includes('-----END PUBLIC KEY-----')) {
    throw new Error(`Invalid ${label} format`)
  }
}

export function derivePublicKeyPem(privateKeyPem) {
  if (typeof privateKeyPem !== 'string' || !privateKeyPem.includes('-----BEGIN')) {
    throw new Error('Invalid JWT private key format')
  }

  return createPublicKey(privateKeyPem).export({
    type: 'spki',
    format: 'pem',
  }).toString()
}

export async function publicKeyPemToJwk(publicKeyPem) {
  assertPem(publicKeyPem)
  const jwk = createPublicKey(publicKeyPem).export({ format: 'jwk' })
  const canonicalJwk = {
    kty: jwk.kty,
    n: jwk.n,
    e: jwk.e,
  }
  const kid = createHash('sha256')
    .update(JSON.stringify({ e: canonicalJwk.e, kty: canonicalJwk.kty, n: canonicalJwk.n }))
    .digest('base64url')

  return {
    ...jwk,
    kid,
    alg: MARKETPLACE_JWT_ALGORITHM,
    use: 'sig',
  }
}

export async function getSigningKeyMetadata(privateKeyPem) {
  const publicKeyPem = derivePublicKeyPem(privateKeyPem)
  const publicJwk = await publicKeyPemToJwk(publicKeyPem)
  return { kid: publicJwk.kid, publicJwk, publicKeyPem }
}

function readStaticJwks() {
  try {
    const parsed = JSON.parse(fs.readFileSync(STATIC_JWKS_PATH, 'utf8'))
    if (!Array.isArray(parsed?.keys)) return []
    return parsed.keys.filter((key) => (
      key
      && key.kty === 'RSA'
      && key.alg === MARKETPLACE_JWT_ALGORITHM
      && key.use === 'sig'
      && typeof key.kid === 'string'
      && typeof key.n === 'string'
      && typeof key.e === 'string'
    ))
  } catch (error) {
    if (error?.code !== 'ENOENT') {
      throw new Error(`Unable to read Marketplace JWKS: ${error.message}`, { cause: error })
    }
    return []
  }
}

function readConfiguredPublicKey() {
  if (process.env.JWT_PUBLIC_KEY) return process.env.JWT_PUBLIC_KEY
  return fs.readFileSync(STATIC_PUBLIC_KEY_PATH, 'utf8')
}

/**
 * Return the Marketplace signing key set with the active key first.
 *
 * The committed JWKS contains the active and previous public keys generated by
 * the rotation workflow. Deriving the first key from JWT_PRIVATE_KEY keeps the
 * endpoint authoritative during the short deployment window in which the
 * application environment and the committed public files are updated at
 * different times.
 */
export async function getMarketplaceJwks() {
  const currentPublicKeyPem = process.env.JWT_PRIVATE_KEY
    ? derivePublicKeyPem(process.env.JWT_PRIVATE_KEY)
    : readConfiguredPublicKey()
  const currentJwk = await publicKeyPemToJwk(currentPublicKeyPem)
  const previousJwks = []

  if (process.env.JWT_PREVIOUS_PUBLIC_KEY) {
    previousJwks.push(await publicKeyPemToJwk(process.env.JWT_PREVIOUS_PUBLIC_KEY))
  }
  previousJwks.push(...readStaticJwks())

  const keys = []
  const seenKids = new Set()
  for (const key of [currentJwk, ...previousJwks]) {
    if (!seenKids.has(key.kid)) {
      seenKids.add(key.kid)
      keys.push(key)
    }
    if (keys.length === 2) break
  }

  return { keys }
}
